--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alexbgameson/PMMPPlugins
branches:
- master
projects:
  BuildUHC:
    path: BuildUHC/
  HardCoreFactionsPE:
    path: HardCoreFactionsPE/
  PureEntitiesX-master:
    path: PureEntitiesX-master/
  ReportUI-master:
    path: ReportUI-master/
  SimpleShopGUI-master:
    path: SimpleShopGUI-master/
...
